name: opensurge
base: core20
adopt-info: opensurge

grade: stable
confinement: strict

apps:
  opensurge:
    command: bin/desktop-launch $SNAP/usr/games/opensurge
    desktop: usr/share/applications/opensurge.desktop
    common-id: org.opensurge2d.OpenSurge
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
      - opengl
      - joystick

layout:
  /usr/share/games/opensurge:
    bind: $SNAP/usr/share/games/opensurge

parts:
  opensurge:
    after: [desktop-glib-only, liballegro5, surgescript]
    source: https://github.com/alemart/opensurge.git
    source-tag: v0.6.0.3
    plugin: cmake
    parse-info: [usr/share/metainfo/opensurge.appdata.xml]
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBLEEDING_EDGE=OFF
      - -DALLEGRO_MONOLITH=OFF
      - -DDESKTOP_INSTALL=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DGAME_DATADIR=/usr/share/games/opensurge
      - -DGAME_BINDIR=/usr/games
      - -DDESKTOP_ENTRY_PATH=/usr/share/applications
      - -DDESKTOP_ICON_PATH=/usr/share/pixmaps
      - -DDESKTOP_METAINFO_PATH=/usr/share/metainfo
      - -DSURGESCRIPT_INCLUDE_PATH=$SNAPCRAFT_STAGE/usr/include
      - -DSURGESCRIPT_LIBRARY_PATH=$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - -DALLEGRO_INCLUDE_PATH=$SNAPCRAFT_STAGE/usr/include
      - -DALLEGRO_LIBRARY_PATH=$SNAPCRAFT_STAGE/usr/lib/
    build-packages:
      - build-essential
    stage-packages:
      - libasyncns0
      - libatk1.0-0
      - libcairo2
      - libdatrie1
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libjpeg-turbo8
      - libogg0
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpulse0
      - libsndfile1
      - libthai0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libphysfs1

  surgescript:
    source: https://github.com/alemart/surgescript.git
    source-tag: v0.5.6.1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWANT_EXECUTABLE=OFF
      - -DWANT_STATIC=OFF
    build-packages:
      - build-essential

  liballegro5:
    source: https://github.com/liballeg/allegro5/releases/download/5.2.8.0/allegro-5.2.8.0.tar.gz
    source-checksum: sha256/089fcbfab0543caa282cd61bd364793d0929876e3d2bf629380ae77b014e4aa4
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWANT_DEMO=OFF
      - -DWANT_DOCS=OFF
      - -DWANT_EXAMPLES=OFF
      - -DWANT_TESTS=OFF
    build-packages: # lean A5
      - build-essential
      - zlib1g-dev
      - libvorbis-dev
      - libogg-dev
      - libpulse-dev
      - libpng-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - libphysfs-dev
      - libgtk-3-dev
      - libglu1-mesa-dev
      - libgl1-mesa-dev

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
